osx_image: xcode8
language: objective-c

install:
  - gem install cocoapods -v 1.1.0.rc.2 --no-rdoc --no-ri
  - pod repo update --silent

script:
  - pod install --project-directory=Xcode/Testing-iOS
  - pod install --project-directory=Xcode/Testing-macOS
  - set -o pipefail
  - xcodebuild -workspace Xcode/Testing-iOS/XMPPFrameworkTests.xcworkspace -scheme XMPPFrameworkTests -sdk iphonesimulator -destination 'name=iPhone 6' test | xcpretty -c
  - xcodebuild -workspace Xcode/Testing-macOS/XMPPFrameworkTests.xcworkspace -scheme XMPPFrameworkTests -sdk macosx -destination 'platform=OS X,arch=x86_64' test | xcpretty -c
