# references:
# * http://www.objc.io/issue-6/travis-ci.html
osx_image: xcode7.3
language: objective-c

script:
  - pod install --project-directory=Xcode/Testing-iOS
  - pod install --project-directory=Xcode/Testing-macOS
  - xctool -workspace Xcode/Testing-iOS/XMPPFrameworkTests.xcworkspace -scheme XMPPFrameworkTests -sdk iphonesimulator -arch x86_64 test
  - xctool -workspace Xcode/Testing-macOS/XMPPFrameworkTests.xcworkspace -scheme XMPPFrameworkTests -sdk macosx -arch x86_64 test
