osx_image: xcode8
language: objective-c

install:
  - cd Xcode/Testing-iOS
  - bundle install
  - bundle exec pod repo update --silent
  - bundle exec pod install
  - cd ../../
  - cd Xcode/Testing-macOS
  - bundle install
  - bundle exec pod repo update --silent
  - bundle exec pod install
  - cd ../../

script:
  - xcodebuild -workspace Xcode/Testing-iOS/XMPPFrameworkTests.xcworkspace -scheme XMPPFrameworkTests -sdk iphonesimulator -destination 'name=iPhone 6' test
  - xcodebuild -workspace Xcode/Testing-macOS/XMPPFrameworkTests.xcworkspace -scheme XMPPFrameworkTests -sdk macosx -destination 'platform=OS X,arch=x86_64' test
